// palavras.js - Banco de 100 palavras educativas para o Desafio das Palavras
const wordList = [
    { w: "FOTOSSINTESE", h: "Processo das plantas para produzir energia usando a luz solar." },
    { w: "MAMIFERO", h: "Animal que mama quando filhote." },
    { w: "ATMOSFERA", h: "Camada de ar que envolve a Terra." },
    { w: "ESQUELETO", h: "Conjunto de ossos do nosso corpo." },
    { w: "GRAVIDADE", h: "Força que puxa tudo para o centro da Terra." },
    { w: "PLANETA", h: "Corpo celeste que orbita uma estrela, como a Terra." },
    { w: "CONTINENTE", h: "Grande massa de terra cercada por oceanos." },
    { w: "MULTIPLICACAO", h: "Operação matemática de somar várias vezes o mesmo número." },
    { w: "DIVISAO", h: "Operação de repartir algo em partes iguais." },
    { w: "SUBSTANTIVO", h: "Classe de palavra que dá nome aos seres e objetos." },
    { w: "REPUBLICA", h: "Forma de governo onde o povo elege o presidente." },
    { w: "RECICLAGEM", h: "Transformar lixo em algo novo." },
    { w: "ASTRONAUTA", h: "Pessoa que viaja para o espaço." },
    { w: "EQUADOR", h: "Linha imaginária que divide a Terra em Norte e Sul." },
    { w: "DICIONARIO", h: "Livro que explica o significado das palavras." },
    { w: "TRIANGULO", h: "Forma geométrica de três lados." },
    { w: "HIDROGRAFIA", h: "Estudo das águas do planeta." },
    { w: "SINONIMO", h: "Palavra com significado parecido." },
    { w: "ANTONIMO", h: "Palavra com significado oposto." },
    { w: "AMAZONIA", h: "A maior floresta tropical do mundo." },
    { w: "HIGIENE", h: "Cuidados com a limpeza para manter a saúde." },
    { w: "ALFABETO", h: "Conjunto de letras usadas para escrever." },
    { w: "NUMERAL", h: "Símbolo que representa uma quantidade." },
    { w: "GEOGRAFIA", h: "Ciência que estuda a Terra e seus fenômenos." },
    { w: "HISTORIA", h: "Estudo do passado da humanidade." },
    { w: "MATEMATICA", h: "Ciência dos números, formas e quantidades." },
    { w: "CIENCIAS", h: "Estudo da natureza e seus fenômenos." },
    { w: "PORTUGUES", h: "Língua oficial do Brasil." },
    { w: "LITERATURA", h: "Arte de escrever livros e poesias." },
    { w: "ARTE", h: "Expressão criativa através de diferentes formas." },
    { w: "MUSICA", h: "Arte de combinar sons harmoniosamente." },
    { w: "ESPORTE", h: "Atividade física com regras e competição." },
    { w: "SAUDE", h: "Estado de bem-estar físico e mental." },
    { w: "ALIMENTACAO", h: "Ato de se alimentar para obter nutrientes." },
    { w: "NUTRICAO", h: "Ciência que estuda os alimentos e seus efeitos." },
    { w: "ECOLOGIA", h: "Estudo das relações entre seres vivos e ambiente." },
    { w: "BIODIVERSIDADE", h: "Variedade de espécies vivas em um ecossistema." },
    { w: "ENERGIA", h: "Capacidade de realizar trabalho ou produzir calor." },
    { w: "ELETRICIDADE", h: "Energia proveniente do movimento de elétrons." },
    { w: "MAGNETISMO", h: "Propriedade de atrair ou repelir objetos metálicos." },
    { w: "TEMPERATURA", h: "Medida do calor ou frio de um corpo." },
    { w: "CLIMA", h: "Conjunto das condições atmosféricas de uma região." },
    { w: "SOL", h: "Estrela central do nosso sistema solar." },
    { w: "LUA", h: "Satélite natural da Terra." },
    { w: "ESTRELA", h: "Corpo celeste que emite luz própria." },
    { w: "GALAXIA", h: "Conjunto de bilhões de estrelas, planetas e gases." },
    { w: "UNIVERSO", h: "Tudo o que existe: matéria, energia, espaço e tempo." },
    { w: "EVOLUCAO", h: "Processo de mudança das espécies ao longo do tempo." },
    { w: "GENETICA", h: "Ciência que estuda a hereditariedade." },
    { w: "CELULA", h: "Unidade básica de todos os seres vivos." },
    { w: "ORGAOS", h: "Partes do corpo que realizam funções específicas." },
    { w: "SISTEMA", h: "Conjunto de órgãos que trabalham juntos." },
    { w: "RESPIRACAO", h: "Processo de troca de gases com o ambiente." },
    { w: "DIGESTAO", h: "Processo de transformação dos alimentos em nutrientes." },
    { w: "CIRCULACAO", h: "Movimento do sangue pelo corpo." },
    { w: "NERVOSO", h: "Sistema responsável por transmitir informações no corpo." },
    { w: "MUSCULO", h: "Tecido que permite o movimento do corpo." },
    { w: "ESQUELETICO", h: "Relativo aos ossos do corpo." },
    { w: "SENTIDOS", h: "Visão, audição, tato, paladar e olfato." },
    { w: "PERCEPCAO", h: "Capacidade de interpretar informações dos sentidos." },
    { w: "MEMORIA", h: "Capacidade de armazenar e recuperar informações." },
    { w: "APRENDIZADO", h: "Processo de adquirir conhecimento ou habilidade." },
    { w: "EDUCACAO", h: "Processo de desenvolvimento das capacidades intelectuais." },
    { w: "ESCOLA", h: "Instituição dedicada ao ensino." },
    { w: "PROFESSOR", h: "Pessoa que ensina e transmite conhecimentos." },
    { w: "ALUNO", h: "Pessoa que recebe ensino em uma instituição." },
    { w: "FAMILIA", h: "Grupo de pessoas ligadas por parentesco." },
    { w: "COMUNIDADE", h: "Conjunto de pessoas que vivem em uma mesma área." },
    { w: "SOCIEDADE", h: "Conjunto de indivíduos que compartilham cultura." },
    { w: "CULTURA", h: "Conjunto de conhecimentos, crenças e costumes." },
    { w: "TRADICAO", h: "Costumes e práticas transmitidos entre gerações." },
    { w: "FESTA", h: "Celebração ou comemoração de um evento." },
    { w: "BRINCADEIRA", h: "Atividade lúdica para diversão." },
    { w: "JOGO", h: "Atividade com regras para entretenimento ou competição." },
    { w: "DIVERSÃO", h: "Atividade que proporciona prazer e entretenimento." },
    { w: "LAZER", h: "Tempo livre para atividades de descanso e diversão." },
    { w: "TRABALHO", h: "Atividade realizada para produzir algo." },
    { w: "PROFISSAO", h: "Ocupação ou atividade profissional." },
    { w: "TECNOLOGIA", h: "Conjunto de conhecimentos técnicos e científicos." },
    { w: "COMPUTADOR", h: "Máquina eletrônica que processa informações." },
    { w: "INTERNET", h: "Rede mundial de computadores conectados." },
    { w: "COMUNICACAO", h: "Processo de transmitir informações." },
    { w: "INFORMACAO", h: "Dado ou conhecimento transmitido." },
    { w: "CONHECIMENTO", h: "Compreensão ou familiaridade adquirida." },
    { w: "SABEDORIA", h: "Aplicação prática do conhecimento." },
    { w: "INTELIGENCIA", h: "Capacidade de aprender, compreender e raciocinar." },
    { w: "CRIATIVIDADE", h: "Capacidade de criar coisas novas e originais." },
    { w: "IMAGINACAO", h: "Faculdade de formar imagens mentais." },
    { w: "SONHO", h: "Sequência de imagens e emoções durante o sono." },
    { w: "REALIDADE", h: "Tudo o que existe de fato, não imaginário." },
    { w: "VERDADE", h: "Conformidade com os fatos ou a realidade." },
    { w: "JUSTICA", h: "Princípio moral que dá a cada um o que é seu." },
    { w: "LIBERDADE", h: "Direito de agir conforme a própria vontade." },
    { w: "RESPEITO", h: "Consideração pelo valor de alguém ou algo." },
    { w: "SOLIDARIEDADE", h: "Apoio mútuo em situações difíceis." },
    { w: "COOPERACAO", h: "Ação conjunta para alcançar um objetivo comum." },
    { w: "AMIZADE", h: "Relação afetiva entre pessoas." },
    { w: "AMOR", h: "Sentimento profundo de afeição e dedicação." },
    { w: "FELICIDADE", h: "Estado de contentamento e satisfação." },
    { w: "PAZ", h: "Estado de tranquilidade e ausência de conflito." },
    { w: "HARMONIA", h: "Combinação agradável e equilibrada de elementos." },
    { w: "BELEZA", h: "Qualidade do que é belo ou agradável aos sentidos." },
    { w: "NATUREZA", h: "Conjunto de tudo o que existe no mundo natural." }
];
