// perguntas.js
// ============== BANCO DE 100+ PERGUNTAS ==============     
if (typeof questionBank === 'undefined') {
    var questionBank = [  // Use 'var' ou 'let' sem 'const'
            // MATEMÁTICA (20 perguntas)
            {q: "Quanto é 2 + 2?", a: ["3", "4", "5", "6"], c: "4"},
            {q: "Quanto é 5 + 3?", a: ["6", "7", "8", "9"], c: "8"},
            {q: "Quanto é 10 - 5?", a: ["3", "4", "5", "6"], c: "5"},
            {q: "Quanto é 3 × 3?", a: ["6", "9", "12", "15"], c: "9"},
            {q: "Quanto é 8 ÷ 2?", a: ["2", "3", "4", "5"], c: "4"},
            {q: "Qual é o dobro de 7?", a: ["12", "14", "16", "18"], c: "14"},
            {q: "Qual é a metade de 20?", a: ["8", "10", "12", "14"], c: "10"},
            {q: "Quanto é 4 × 5?", a: ["16", "18", "20", "22"], c: "20"},
            {q: "Quanto é 15 ÷ 3?", a: ["3", "4", "5", "6"], c: "5"},
            {q: "Qual número vem depois do 99?", a: ["98", "99", "100", "101"], c: "100"},
            {q: "Quantos lados tem um triângulo?", a: ["2", "3", "4", "5"], c: "3"},
            {q: "Quantos lados tem um quadrado?", a: ["3", "4", "5", "6"], c: "4"},
            {q: "Quanto é 25 + 25?", a: ["40", "45", "50", "55"], c: "50"},
            {q: "Quanto é 100 - 30?", a: ["60", "70", "80", "90"], c: "70"},
            {q: "Qual é o dobro de 12?", a: ["22", "24", "26", "28"], c: "24"},
            {q: "Quanto é 6 × 4?", a: ["20", "22", "24", "26"], c: "24"},
            {q: "Quanto é 36 ÷ 6?", a: ["4", "5", "6", "7"], c: "6"},
            {q: "Qual número é maior: 45 ou 54?", a: ["45", "54", "São iguais"], c: "54"},
            {q: "Quantos minutos tem uma hora?", a: ["50", "60", "70", "80"], c: "60"},
            {q: "Quantos dias tem uma semana?", a: ["5", "6", "7", "8"], c: "7"},
            
            
            // CIÊNCIAS E NATUREZA (25 perguntas)
            {q: "Qual é a cor do céu em um dia sem nuvens?", a: ["Verde", "Azul", "Amarelo", "Vermelho"], c: "Azul"},
            {q: "Qual animal faz 'Miau'?", a: ["Cachorro", "Gato", "Vaca", "Galinha"], c: "Gato"},
            {q: "Qual é o maior animal do mundo?", a: ["Elefante", "Girafa", "Baleia Azul", "Tubarão"], c: "Baleia Azul"},
            {q: "Que animal é conhecido como 'rei da selva'?", a: ["Elefante", "Leão", "Tigre", "Gorila"], c: "Leão"},
            {q: "Quantas patas tem um cachorro?", a: ["2", "3", "4", "5"], c: "4"},
            {q: "Que cor tem a grama?", a: ["Azul", "Verde", "Vermelho", "Amarelo"], c: "Verde"},
            {q: "Qual fruta é vermelha e tem sementes na casca?", a: ["Banana", "Maçã", "Morango", "Laranja"], c: "Morango"},
            {q: "Qual é a fruta favorita dos macacos?", a: ["Maçã", "Banana", "Uva", "Pera"], c: "Banana"},
            {q: "Qual destes animais voa?", a: ["Cachorro", "Gato", "Pássaro", "Peixe"], c: "Pássaro"},
            {q: "O que as plantas precisam para crescer?", a: ["Água", "Fogo", "Gelo", "Plástico"], c: "Água"},
            {q: "Quantas estações tem o ano?", a: ["2", "3", "4", "5"], c: "4"},
            {q: "Qual é a estação mais quente?", a: ["Primavera", "Verão", "Outono", "Inverno"], c: "Verão"},
            {q: "O que o sol nos dá?", a: ["Água", "Luz e calor", "Gelo", "Vento"], c: "Luz e calor"},
            {q: "Quantas cores tem o arco-íris?", a: ["5", "6", "7", "8"], c: "7"},
            {q: "Qual planeta é conhecido como 'planeta vermelho'?", a: ["Terra", "Marte", "Júpiter", "Saturno"], c: "Marte"},
            {q: "Qual é o planeta mais próximo do Sol?", a: ["Vênus", "Terra", "Marte", "Mercúrio"], c: "Mercúrio"},
            {q: "Qual destes vive na água?", a: ["Gato", "Coelho", "Peixe", "Cachorro"], c: "Peixe"},
            {q: "Que animal produz leite?", a: ["Galinha", "Vaca", "Porco", "Cavalo"], c: "Vaca"},
            {q: "O que é a neve?", a: ["Água quente", "Água congelada", "Terra", "Fogo"], c: "Água congelada"},
            {q: "Qual destes é um inseto?", a: ["Gato", "Cachorro", "Borboleta", "Peixe"], c: "Borboleta"},
            {q: "Que fruta é laranja e tem vitamina C?", a: ["Maçã", "Banana", "Laranja", "Uva"], c: "Laranja"},
            {q: "Quantas asas tem uma borboleta?", a: ["1", "2", "3", "4"], c: "4"},
            {q: "O que as árvores produzem que nós respiramos?", a: ["Dióxido de carbono", "Oxigênio", "Água", "Fumaça"], c: "Oxigênio"},
            {q: "Qual destes é um mamífero marinho?", a: ["Águia", "Golfinho", "Cobra", "Rã"], c: "Golfinho"},
            {q: "Que animal tem uma concha?", a: ["Cachorro", "Gato", "Caracol", "Pássaro"], c: "Caracol"},
                      
            // GEOGRAFIA (20 perguntas)
            {q: "Qual é a capital do Brasil?", a: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador"], c: "Brasília"},
            {q: "Em que continente fica o Brasil?", a: ["Ásia", "Europa", "América do Sul", "África"], c: "América do Sul"},
            {q: "Qual oceano banha o litoral brasileiro?", a: ["Pacífico", "Atlântico", "Índico", "Ártico"], c: "Atlântico"},
            {q: "Qual é o maior país do mundo?", a: ["China", "Estados Unidos", "Rússia", "Brasil"], c: "Rússia"},
            {q: "Qual é a capital da França?", a: ["Londres", "Berlim", "Paris", "Madri"], c: "Paris"},
            {q: "Em que país fica a Torre Eiffel?", a: ["Itália", "França", "Espanha", "Alemanha"], c: "França"},
            {q: "Qual é a capital dos Estados Unidos?", a: ["Nova York", "Los Angeles", "Washington D.C.", "Chicago"], c: "Washington D.C."},
            {q: "Qual é o maior deserto do mundo?", a: ["Deserto do Saara", "Deserto da Arábia", "Deserto de Gobi", "Deserto do Atacama"], c: "Deserto do Saara"},
            {q: "Qual é o rio mais longo do mundo?", a: ["Rio Amazonas", "Rio Nilo", "Rio Yangtzé", "Rio Mississippi"], c: "Rio Nilo"},
            {q: "Quantos estados tem o Brasil?", a: ["25", "26", "27", "28"], c: "26"},
            {q: "Qual é a língua oficial do Brasil?", a: ["Espanhol", "Inglês", "Português", "Francês"], c: "Português"},
            {q: "Que país tem formato de bota?", a: ["França", "Espanha", "Itália", "Portugal"], c: "Itália"},
            {q: "Qual é a capital da Argentina?", a: ["Buenos Aires", "Santiago", "Lima", "Montevidéu"], c: "Buenos Aires"},
            {q: "Qual continente é conhecido como 'berço da humanidade'?", a: ["Ásia", "Europa", "África", "América"], c: "África"},
            {q: "Que país é famoso pela Torre de Pisa?", a: ["França", "Itália", "Espanha", "Grécia"], c: "Itália"},
            {q: "Em que país fica a Muralha da China?", a: ["Japão", "China", "Coreia", "Vietnã"], c: "China"},
            {q: "Qual é a capital do Japão?", a: ["Pequim", "Seul", "Tóquio", "Bangkok"], c: "Tóquio"},
            {q: "Que país tem a bandeira vermelha com uma estrela amarela?", a: ["China", "Japão", "Coreia", "Vietnã"], c: "China"},
            {q: "Qual é o menor país do mundo?", a: ["Mônaco", "Vaticano", "San Marino", "Liechtenstein"], c: "Vaticano"},
            {q: "Que continente é a Austrália?", a: ["Ásia", "Europa", "Oceania", "América"], c: "Oceania"},
            
            // PORTUGUÊS (20 perguntas)
            {q: "Quantas vogais tem o alfabeto português?", a: ["4", "5", "6", "7"], c: "5"},
            {q: "Qual a primeira letra do alfabeto?", a: ["B", "C", "A", "D"], c: "A"},
            {q: "Qual a última letra do alfabeto?", a: ["X", "Y", "Z", "W"], c: "Z"},
            {q: "Complete: O ____ está quente. (Sol/Sal)", a: ["Sol", "Sal", "Sul", "Sel"], c: "Sol"},
            {q: "Qual é o plural de 'casa'?", a: ["Casas", "Caso", "Casos", "Casa"], c: "Casas"},
            {q: "Qual é o antônimo de 'grande'?", a: ["Médio", "Gigante", "Pequeno", "Alto"], c: "Pequeno"},
            {q: "Qual é o sinônimo de 'feliz'?", a: ["Triste", "Alegre", "Bravo", "Cansado"], c: "Alegre"},
            {q: "Quantas sílabas tem a palavra 'escola'?", a: ["2", "3", "4", "5"], c: "3"},
            {q: "Qual destas é uma vogal?", a: ["B", "C", "E", "D"], c: "E"},
            {q: "Qual destas é uma consoante?", a: ["A", "E", "I", "M"], c: "M"},
            {q: "Como se escreve o número 7 por extenso?", a: ["Sete", "Seta", "Cete", "Seti"], c: "Sete"},
            {q: "Qual é o aumentativo de 'casa'?", a: ["Casebre", "Casinha", "Casarão", "Casota"], c: "Casarão"},
            {q: "Qual é o diminutivo de 'gato'?", a: ["Gatão", "Gatuno", "Gatinho", "Gatal"], c: "Gatinho"},
            {q: "Complete: Eu _____ para escola. (vou/voou)", a: ["Vou", "Voou", "Vão", "Vem"], c: "Vou"},
            {q: "Quantas letras tem a palavra 'borboleta'?", a: ["8", "9", "10", "11"], c: "9"},
            {q: "Qual destas palavras está escrita corretamente?", a: ["Cazal", "Cachorro", "Caxorro", "Caza"], c: "Cachorro"},
            {q: "O que é uma 'rima'?", a: ["Números iguais", "Palavras com sons parecidos", "Cores iguais", "Formas iguais"], c: "Palavras com sons parecidos"},
            {q: "Qual é o gênero de 'menino'?", a: ["Feminino", "Masculino", "Neutro"], c: "Masculino"},
            {q: "Qual é o feminino de 'rei'?", a: ["Reia", "Rainha", "Reizinho", "Realeza"], c: "Rainha"},
            {q: "O que é uma 'silaba'?", a: ["Uma letra", "Um som", "Um pedaço de palavra", "Um ponto"], c: "Um pedaço de palavra"},
            
            // CULTURA GERAL (20 perguntas)
            {q: "Quantos meses tem um ano?", a: ["10", "11", "12", "13"], c: "12"},
            {q: "Que forma tem uma bola de futebol?", a: ["Quadrada", "Redonda", "Triangular", "Retangular"], c: "Redonda"},
            {q: "Quem escreveu 'O Pequeno Príncipe'?", a: ["Monteiro Lobato", "Machado de Assis", "Antoine de Saint-Exupéry", "José de Alencar"], c: "Antoine de Saint-Exupéry"},
            {q: "Quantos times jogam em uma partida de futebol?", a: ["1", "2", "3", "4"], c: "2"},
            {q: "Qual é a cor do semáforo que significa 'pare'?", a: ["Verde", "Amarelo", "Vermelho", "Azul"], c: "Vermelho"},
            {q: "Que instrumento musical tem cordas e é tocado com arco?", a: ["Piano", "Violino", "Flauta", "Bateria"], c: "Violino"},
            {q: "Quantas cores tem a bandeira do Brasil?", a: ["3", "4", "5", "6"], c: "4"},
            {q: "Que dia é comemorado o Natal?", a: ["25 de dezembro", "31 de dezembro", "1 de janeiro", "6 de janeiro"], c: "25 de dezembro"},
            {q: "Quantas horas tem um dia?", a: ["12", "24", "36", "48"], c: "24"},
            {q: "Que ferramenta usamos para cortar papel?", a: ["Martelo", "Tesoura", "Chave de fenda", "Serra"], c: "Tesoura"},
            {q: "Que fruto usamos para fazer azeite?", a: ["Maçã", "Laranja", "Azeitona", "Uva"], c: "Azeitona"},
            {q: "Que bebida é feita de leite fermentado?", a: ["Suco", "Refrigerante", "Iogurte", "Café"], c: "Iogurte"},
            {q: "Qual é o oposto do dia?", a: ["Manhã", "Tarde", "Noite", "Madrugada"], c: "Noite"},
            {q: "Que parte do corpo usamos para ouvir?", a: ["Olhos", "Orelhas", "Boca", "Nariz"], c: "Orelhas"},
            {q: "Que veículo tem duas rodas e guidão?", a: ["Carro", "Ônibus", "Bicicleta", "Caminhão"], c: "Bicicleta"},
            {q: "O que usamos para escrever no papel?", a: ["Pincel", "Lápis", "Martelo", "Tesoura"], c: "Lápis"},
            {q: "Que objeto usamos para ver as horas?", a: ["Rádio", "Relógio", "Telefone", "Livro"], c: "Relógio"},
            {q: "Que alimento é feito de trigo e comemos com manteiga?", a: ["Arroz", "Feijão", "Pão", "Batata"], c: "Pão"},
            {q: "Que brinquedo voa no ar com uma linha?", a: ["Bola", "Pipa", "Carrinho", "Boneca"], c: "Pipa"},
            {q: "Que dia da semana vem depois da terça-feira?", a: ["Segunda", "Quarta", "Quinta", "Sexta"], c: "Quarta"}
        ];
  console.log("✅ Banco de perguntas criado:", questionBank.length, "perguntas");
} else {
    console.warn("⚠️ questionBank já foi definido anteriormente");
}
